### ISSUE TITLE
Session is ended but not removed from website.

### ISSUE THREAD

**Issue by Logan1x** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#71] opened 2017-07-10 13:53 UTC
the last session held on july 8 was not removed from website it showing register now till now so i think we should update "register now " to something else.

**Comment by vaibhavsingh97** [comment] 2017-07-10 15:05
Duplicate of #1

**Comment by Logan1x** [comment] 2017-07-10 15:44
@vaibhavsingh97  we decided to remove past session from website on slack but its not removed i dont see anything like this on #1 .

**Comment by Logan1x** [comment] 2017-07-10 15:45
we should discuss about that we should remove session or add a block of past session.

**Comment by vaibhavsingh97** [comment] 2017-07-10 16:44
Actually, it's hard coded and we need some efficient method so that if the session is ended than it should automatically move to the previous session and new session would be displayed. Also, navigating to session redirect to youtube so the expected behavior should display all the videos by fetching through API.
I will work in this once I finish #48. If you have some idea than we can collaborate

**Comment by Logan1x** [comment] 2017-07-11 04:55
@vaibhavsingh97 the api redirecting to eventbrite and past event's are showing event ended to me so it's fine now but have a look at it #72

**Comment by tapasweni-pathak** [comment] 2017-07-14 22:46
We'll update after we finalize next one.

**Closed as completed** 2017-07-18 14:56 UTC
